
using System.Collections;

public class BodyMirabilarMail  {
	
	static string myString = "";

	public static string bodyMirabilar ()
	{
				myString = myString + "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
				myString = myString + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
				myString = myString + "    <head>\n";
				myString = myString + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
				myString = myString + "        <title>prova</title>\n";
				myString = myString + "		\n";
				myString = myString + "    <style type=\"text/css\">\n";
				myString = myString + "		#outlook a{\n";
				myString = myString + "			padding:0;\n";
				myString = myString + "		}\n";
				myString = myString + "		body{\n";
				myString = myString + "			width:100% !important;\n";
				myString = myString + "		}\n";
				myString = myString + "		.ReadMsgBody{\n";
				myString = myString + "			width:100%;\n";
				myString = myString + "		}\n";
				myString = myString + "		.ExternalClass{\n";
				myString = myString + "			width:100%;\n";
				myString = myString + "		}\n";
				myString = myString + "		body{\n";
				myString = myString + "			-webkit-text-size-adjust:none;\n";
				myString = myString + "		}\n";
				myString = myString + "		body{\n";
				myString = myString + "			margin:0;\n";
				myString = myString + "			padding:0;\n";
				myString = myString + "		}\n";
				myString = myString + "		img{\n";
				myString = myString + "			border:0;\n";
				myString = myString + "			height:auto;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			outline:none;\n";
				myString = myString + "			text-decoration:none;\n";
				myString = myString + "		}\n";
				myString = myString + "		table td{\n";
				myString = myString + "			border-collapse:collapse;\n";
				myString = myString + "		}\n";
				myString = myString + "		#backgroundTable{\n";
				myString = myString + "			height:100% !important;\n";
				myString = myString + "			margin:0;\n";
				myString = myString + "			padding:0;\n";
				myString = myString + "			width:100% !important;\n";
				myString = myString + "		}\n";
				myString = myString + "		h1,.h1{\n";
				myString = myString + "			color:#363636;\n";
				myString = myString + "			display:block;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:32px;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			letter-spacing:normal;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			margin-top:0;\n";
				myString = myString + "			margin-right:0;\n";
				myString = myString + "			margin-bottom:10px;\n";
				myString = myString + "			margin-left:0;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		h2,.h2{\n";
				myString = myString + "			color:#543680;\n";
				myString = myString + "			display:block;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:40px;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			margin-top:0;\n";
				myString = myString + "			margin-right:0;\n";
				myString = myString + "			margin-bottom:10px;\n";
				myString = myString + "			margin-left:0;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		h3,.h3{\n";
				myString = myString + "			color:#363636;\n";
				myString = myString + "			display:block;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:16px;\n";
				myString = myString + "			font-weight:bold;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			margin-top:0;\n";
				myString = myString + "			margin-right:0;\n";
				myString = myString + "			margin-bottom:10px;\n";
				myString = myString + "			margin-left:0;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		h4,.h4{\n";
				myString = myString + "			color:#26ABE2;\n";
				myString = myString + "			display:block;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:14px;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			margin-top:0;\n";
				myString = myString + "			margin-right:0;\n";
				myString = myString + "			margin-bottom:10px;\n";
				myString = myString + "			margin-left:0;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		#templatePreheader{\n";
				myString = myString + "			background-color:#FFFFFF;\n";
				myString = myString + "		}\n";
				myString = myString + "		.preheaderContent{\n";
				myString = myString + "			color:#707070;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:11px;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		.preheaderContent a:link,.preheaderContent a:visited,.preheaderContent a .yshortcuts {\n";
				myString = myString + "			color:#26ABE2;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			text-decoration:none;\n";
				myString = myString + "		}\n";
				myString = myString + "		#templateHeader{\n";
				myString = myString + "			background-color:#EEEEEE;\n";
				myString = myString + "		}\n";
				myString = myString + "		.headerContent{\n";
				myString = myString + "			color:#363636;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:20px;\n";
				myString = myString + "			font-weight:bold;\n";
				myString = myString + "			line-height:100%;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "			vertical-align:top;\n";
				myString = myString + "		}\n";
				myString = myString + "		.headerContent a:link,.headerContent a:visited,.headerContent a .yshortcuts {\n";
				myString = myString + "			color:#26ABE2;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			text-decoration:underline;\n";
				myString = myString + "		}\n";
				myString = myString + "		#headerImage{\n";
				myString = myString + "			height:auto;\n";
				myString = myString + "			max-width:600px;\n";
				myString = myString + "		}\n";
				myString = myString + "		#templateBody{\n";
				myString = myString + "			background-color:#739c9b;\n";
				myString = myString + "		}\n";
				myString = myString + "		.couponBlock{\n";
				myString = myString + "			background-color:#FFFFFF;\n";
				myString = myString + "			border:1px solid #E5E5E5;\n";
				myString = myString + "		}\n";
				myString = myString + "		.couponContent{\n";
				myString = myString + "			color:#505050;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:12px;\n";
				myString = myString + "			line-height:150%;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		.couponContent a:link,.couponContent a:visited,.couponContent a .yshortcuts {\n";
				myString = myString + "			color:#26ABE2;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			text-decoration:underline;\n";
				myString = myString + "		}\n";
				myString = myString + "		.bodyContent img,.couponContent img{\n";
				myString = myString + "			display:inline;\n";
				myString = myString + "			height:auto;\n";
				myString = myString + "		}\n";
				myString = myString + "		body,#backgroundTable{\n";
				myString = myString + "			background-color:#363636;\n";
				myString = myString + "		}\n";
				myString = myString + "		#templateFooter{\n";
				myString = myString + "			border-top:0;\n";
				myString = myString + "		}\n";
				myString = myString + "		.footerContent{\n";
				myString = myString + "			color:#909090;\n";
				myString = myString + "			font-family:Helvetica;\n";
				myString = myString + "			font-size:11px;\n";
				myString = myString + "			line-height:125%;\n";
				myString = myString + "			text-align:left;\n";
				myString = myString + "		}\n";
				myString = myString + "		.footerContent a:link,.footerContent a:visited,.footerContent a .yshortcuts {\n";
				myString = myString + "			color:#BBBBBB;\n";
				myString = myString + "			font-weight:normal;\n";
				myString = myString + "			text-decoration:none;\n";
				myString = myString + "		}\n";
				myString = myString + "		.footerContent img{\n";
				myString = myString + "			display:inline;\n";
				myString = myString + "		}\n";
				myString = myString + "		#monkeyRewards img{\n";
				myString = myString + "			max-width:180px;\n";
				myString = myString + "		}\n";
				myString = myString + "</style></head>\n";
				myString = myString + "    <body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\" style=\"-webkit-text-size-adjust: none;margin: 0;padding: 0;background-color: #363636;width: 100% !important;\">\n";
				myString = myString + "    	<center>\n";
				myString = myString + "        	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"backgroundTable\" style=\"margin: 0;padding: 0;background-color: #363636;height: 100% !important;width: 100% !important;\">\n";
				myString = myString + "            	<tr>\n";
				myString = myString + "                	<td align=\"center\" valign=\"top\" style=\"height: 100% !important;margin: 0 !important;padding: 0 !important;width: 100% !important;border-collapse: collapse;\">\n";
				myString = myString + "                    \n";
				myString = myString + "                    	<!-- // Preheader \\ -->\n";
				myString = myString + "                        <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\" id=\"templatePreheader\" style=\"background-color: #FFFFFF;\">\n";
				myString = myString + "                        	<tr>\n";
				myString = myString + "                            	<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse;\">\n";
				myString = myString + "                                	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"560\">\n";
				myString = myString + "                                    	<tr>\n";
				myString = myString + "                                            <td valign=\"top\" class=\"preheaderContent\" style=\"padding-right: 20px;border-collapse: collapse;color: #707070;font-family: Helvetica;font-size: 11px;line-height: 100%;text-align: left;\"></td>\n";
				myString = myString + "                                            <!--  -->\n";
				myString = myString + "                                            <td valign=\"top\" width=\"200\" class=\"preheaderContent\" style=\"border-collapse: collapse;color: #707070;font-family: Helvetica;font-size: 11px;line-height: 100%;text-align: left;\">\n";
				myString = myString + "                                                Email not displaying correctly?<br><a href=\"http://us8.campaign-archive1.com/?u=3b13794f0933776b8d0190b78&id=4617800935&e=[UNIQID]\" target=\"_blank\" style=\"color: #26ABE2;font-weight: normal;text-decoration: none;\">View it in your browser</a>.\n";
				myString = myString + "                                            </td>\n";
				myString = myString + "                                            <!--  -->\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                    </table>\n";
				myString = myString + "                                </td>\n";
				myString = myString + "                            </tr>\n";
				myString = myString + "                        </table>\n";
				myString = myString + "                    	<!-- // Preheader \\ -->\n";
				myString = myString + "                        \n";
				myString = myString + "                    	<!-- // Header \\ -->\n";
				myString = myString + "                        <table border=\"0\" cellpadding=\"40\" cellspacing=\"0\" width=\"100%\" id=\"templateHeader\" style=\"background-color: #EEEEEE;\">\n";
				myString = myString + "                        	<tr>\n";
				myString = myString + "                            	<td align=\"center\" valign=\"top\" style=\"padding-bottom: 20px;border-collapse: collapse;\">\n";
				myString = myString + "                                	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"560\">\n";
				myString = myString + "                                    	<tr>\n";
				myString = myString + "                                            <td class=\"headerContent\" style=\"border-collapse: collapse;color: #363636;font-family: Helvetica;font-size: 20px;font-weight: bold;line-height: 100%;text-align: left;vertical-align: top;\">\n";
				myString = myString + "                                                <img src=\"https://gallery.mailchimp.com/3b13794f0933776b8d0190b78/images/26f8804b-1369-45f4-a5dd-7399ade70356.png\" alt=\"\" border=\"0\" style=\"margin: 0;padding: 0;max-width: 560px;border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;\" width=\"560\" id=\"headerImage campaign-icon\">\n";
				myString = myString + "                                            </td>\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                    </table>\n";
				myString = myString + "                                </td>\n";
				myString = myString + "                            </tr>\n";
				myString = myString + "                        </table>\n";
				myString = myString + "                    	<!-- // Header \\ -->\n";
				myString = myString + "\n";
				myString = myString + "                    	<!-- // Body \\ -->\n";
				myString = myString + "                        <table border=\"0\" cellpadding=\"20\" cellspacing=\"0\" width=\"100%\" id=\"templateBody\" style=\"background-color: #739c9b;\">\n";
				myString = myString + "                        	<tr>\n";
				myString = myString + "                            	<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse;\">\n";
				myString = myString + "                                	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"560\">\n";
				myString = myString + "                                        <tr>\n";
				myString = myString + "                                            <td valign=\"top\" style=\"padding-bottom: 20px;border-collapse: collapse;color: #505050;font-family: Helvetica;font-size: 12px;line-height: 150%;text-align: left;\" class=\"couponContent\"><h1 style=\"text-align: center;color: #363636;display: block;font-family: Helvetica;font-size: 32px;font-weight: normal;letter-spacing: normal;line-height: 100%;margin-top: 0;margin-right: 0;margin-bottom: 10px;margin-left: 0;\">Augmenting Your Senses</h1>\n";
				myString = myString + "</td>\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                    	<tr mc:repeatable=\"repeat_1\" mc:repeatindex=\"0\" mc:hideable=\"hideable_repeat_1_1\" mchideable=\"hideable_repeat_1_1\">\n";
				myString = myString + "                                        	<td align=\"center\" colspan=\"2\" style=\"padding-bottom: 40px;border-collapse: collapse;\">\n";
				myString = myString + "                                            	<table border=\"0\" cellpadding=\"20\" cellspacing=\"0\" width=\"560\" class=\"couponBlock\" style=\"background-color: #FFFFFF;border: 1px solid #E5E5E5;\">\n";
				myString = myString + "                                                    <tr>\n";
				myString = myString + "                                                        <td align=\"left\" valign=\"top\" style=\"border-collapse: collapse;\">\n";
				myString = myString + "                                                        	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
				myString = myString + "                                                            	<tr>\n";
				myString = myString + "                                                                	<td colspan=\"2\" valign=\"top\" width=\"455\" style=\"padding-right: 20px;border-collapse: collapse;color: #505050;font-family: Helvetica;font-size: 12px;line-height: 150%;text-align: left;\" class=\"couponContent\"><h2 style=\"color: #543680;display: block;font-family: Helvetica;font-size: 40px;font-weight: normal;line-height: 100%;margin-top: 0;margin-right: 0;margin-bottom: 10px;margin-left: 0;text-align: left;\">20% off</h2>\n";
				myString = myString + "<span style=\"font-size:24px\">by presenting this coupon at the store,thanks for using our AR application!</span></td>\n";
				myString = myString + "                                                                    <td valign=\"top\" width=\"60\" style=\"border-collapse: collapse;\">\n";
				myString = myString + "                                                                    	<div class=\"couponContent\" style=\"color: #505050;font-family: Helvetica;font-size: 12px;line-height: 150%;text-align: left;\"><img align=\"none\" height=\"290\" src=\"https://gallery.mailchimp.com/3b13794f0933776b8d0190b78/images/e5dce3bf-c0cf-4279-8bde-b881e72295b2.jpg\" style=\"width: 290px;height: 290px;margin: 0px;border: 0;line-height: 100%;outline: none;text-decoration: none;display: inline;\" width=\"290\"></div>\n";
				myString = myString + "                                                                    </td>\n";
				myString = myString + "                                                                </tr>\n";
				myString = myString + "                                                            </table>\n";
				myString = myString + "                                                        </td>\n";
				myString = myString + "                                                    </tr>\n";
				myString = myString + "                                                	<tr>\n";
				myString = myString + "                                                    	<td style=\"padding-top: 0;border-collapse: collapse;\">\n";
				myString = myString + "                                                        	<img src=\"https://gallery.mailchimp.com/3b13794f0933776b8d0190b78/images/e2223019-aa22-44c6-97c3-d5f279d5b441.jpg\" alt=\"\" border=\"0\" style=\"margin: 0;padding: 0;max-width: 520px;border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;\" width=\"520\">\n";
				myString = myString + "                                                        </td>\n";
				myString = myString + "                                                    </tr>\n";
				myString = myString + "                                                </table>\n";
				myString = myString + "                                                <img src=\"https://gallery.mailchimp.com/27aac8a65e64c994c4416d6b8/images/coupon_shadow_b.png\" height=\"15\" width=\"560\" style=\"display: block;border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;\">\n";
				myString = myString + "                                            </td>\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                    </table>\n";
				myString = myString + "                                </td>\n";
				myString = myString + "                            </tr>\n";
				myString = myString + "                        </table>\n";
				myString = myString + "                    	<!-- // Body \\ -->\n";
				myString = myString + "\n";
				myString = myString + "                    	<!-- // Footer \\ -->\n";
				myString = myString + "                        <table border=\"0\" cellpadding=\"20\" cellspacing=\"0\" width=\"100%\" id=\"templateFooter\" style=\"border-top: 0;\">\n";
				myString = myString + "                        	<tr>\n";
				myString = myString + "                            	<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse;\">\n";
				myString = myString + "                                	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"560\">\n";
				myString = myString + "                                    	<tr>\n";
				myString = myString + "                                            <td valign=\"top\" class=\"footerContent\" style=\"padding-right: 20px;border-collapse: collapse;color: #909090;font-family: Helvetica;font-size: 11px;line-height: 125%;text-align: left;\"></td>\n";
				myString = myString + "                                            <td valign=\"top\" width=\"200\" class=\"footerContent\" style=\"border-collapse: collapse;color: #909090;font-family: Helvetica;font-size: 11px;line-height: 125%;text-align: left;\"></td>\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                        <tr>\n";
				myString = myString + "                                        	<td colspan=\"2\" valign=\"top\" class=\"footerContent\" style=\"padding-top: 20px;border-collapse: collapse;color: #909090;font-family: Helvetica;font-size: 11px;line-height: 125%;text-align: left;\"></td>\n";
				myString = myString + "                                        </tr>\n";
				myString = myString + "                                    </table>\n";
				myString = myString + "                                </td>\n";
				myString = myString + "                            </tr>\n";
				myString = myString + "                        </table>\n";
				myString = myString + "                    	<!-- // Footer \\ -->\n";
				myString = myString + "                    \n";
				myString = myString + "                    </td>\n";
				myString = myString + "                </tr>\n";
				myString = myString + "            </table>\n";
				myString = myString + "        </center>\n";
				myString = myString + "                <center>\n";
				myString = myString + "                <br>\n";
				myString = myString + "                <br>\n";
				myString = myString + "                <br>\n";
				myString = myString + "                <br>\n";
				myString = myString + "                <br>\n";
				myString = myString + "                <br>\n";

		return myString;
		}


}
